characters = [
    {
        "index": 0,
        "class": "taiscrap",
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,
        "una": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 1,
        "class": "bard",
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,
        "una": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 2,
        "class": "bard",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": False,
        "una": True,
        "guildDonation": False,
        "rapport": False,
    },
    {
        "index": 3,
        "class": "summoner",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "una": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 4,
        "class": "bard",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "una": True,
        "guildDonation": False,
        "rapport": False,
    },
    {
        "index": 5,
        "class": "bard",
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,
        "una": True,
        "guildDonation": False,
        "rapport": False,
    },
    {
        "index": 6,
        "class": "paladin",
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,
        "una": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 7,
        "class": "glavier",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": False,
        "una": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 8,
        "class": "slayer",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": False,
        "una": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 9,
        "class": "deathblade",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "una": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 10,
        "class": "shockscrap",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "lopang": False,
        "una": True,
        "guildDonation": True,
        "rapport": False,
    },
]
